CCAVENUE_MERCHANT_ID: '2110298'
CCAVENUE_ACCESS_CODE: "AVWP23KB52BT68PWTB"
CCAVENUE_WORKING_KEY: "EEF6E4B45E3762C6BEC933487EE88EC5"
# CCAVENUE_MODE: 'LIVE'
CCAVENUE_MODE: 'TEST'


# CCAVENUE_MERCHANT_ID: '2032755'
# CCAVENUE_ACCESS_CODE: "AVUL19KB28AU82LUUA"
# CCAVENUE_WORKING_KEY: "8C2A32E58B81A1584418FFEA525BB3D5"
# CCAVENUE_MODE: 'TEST'

